[tool.poetry]
name = "gpt-from-scratch"
version = "0.1.0"
description = ""
authors = ["Thierry <thierrysantoos123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
